package br.com.simpleapp.rememberyou.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "STATUS_SEND".
 */
public class StatusSend {

    private Long id;
    private String name;
    /** Not-null value. */
    private String email;
    private String emotion;
    private Integer state;
    private java.util.Date dateTime;

    public StatusSend() {
    }

    public StatusSend(Long id) {
        this.id = id;
    }

    public StatusSend(Long id, String name, String email, String emotion, Integer state, java.util.Date dateTime) {
        this.id = id;
        this.name = name;
        this.email = email;
        this.emotion = emotion;
        this.state = state;
        this.dateTime = dateTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getEmail() {
        return email;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEmail(String email) {
        this.email = email;
    }

    public String getEmotion() {
        return emotion;
    }

    public void setEmotion(String emotion) {
        this.emotion = emotion;
    }

    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

    public java.util.Date getDateTime() {
        return dateTime;
    }

    public void setDateTime(java.util.Date dateTime) {
        this.dateTime = dateTime;
    }

}
